### ISSUE TITLE
config [timeout: :infinity] does not seem to be working

### ISSUE THREAD

**Issue by thisdotrob** [HashNuke/hound#102]
My config:
```
config :hound, driver: "phantomjs"
config :hound, http: [timeout: :infinity]
config :hound, http: [recv_timeout: :infinity]
```

But I am still getting timeout errors when doing `navigate_to`:
```
** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :timeout}}
      (hound) lib/hound/request_utils.ex:43: Hound.RequestUtils.send_req/4
```

**Comment by tuvistavie** [comment]
@thisdotrob Thank you for reporting, I am going to give it a look!

**Comment by tuvistavie** [comment]
@thisdotrob I am not really sure why this is happening yet, but it seems that it is fixed when removing the `_build` directory and recompiling.
I am going to investigate a little more, but could you try this temporary fix for now.
Thank you!

**Comment by HashNuke** [comment]
@tuvistavie This seems like a hackney bug that I came across recently (that affected httpoison). It has been fixed since.

Closing this.

**Comment by cwc** [comment]
This bug still exists. The HTTP options are read from the application config here: https://github.com/HashNuke/hound/blob/master/lib/hound/request_utils.ex#L4-L6

However, because they are assigned to the constant `@http_options`, the value of the config is only evaluated *at compile time*. This is why the behavior is "fixed" when Hound is recompiled.

I would recommend replacing references to `@http_options` (e.g. [here](https://github.com/HashNuke/hound/blob/master/lib/hound/request_utils.ex#L43)), `@retry_time`, and any similar values meant to be configured at runtime with direct calls to `Application.get_env`, rather than compile-time constants.
